# Generated by Django 4.2.5 on 2023-09-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="item",
        ),
        migrations.AddField(
            model_name="category",
            name="item",
            field=models.ManyToManyField(to="auctions.listing"),
        ),
    ]
