# Generated by Django 4.2.5 on 2023-09-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_remove_category_item_category_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="item",
            field=models.ManyToManyField(related_name="item", to="auctions.listing"),
        ),
    ]
