# Generated by Django 4.2.5 on 2023-09-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_alter_category_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="image",
            field=models.URLField(max_length=400, null=True),
        ),
    ]
