# Generated by Django 4.2.5 on 2023-09-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_listing_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="item",
            field=models.ManyToManyField(
                related_name="category", to="auctions.listing"
            ),
        ),
    ]
